[package]
name = "test-rust-pugixml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pugixml = { path = "./rust-pugixml" }
