[package]
name = "test-rust-dummy-xml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dummy_xml = "0.1.6"
